---
name: Release

on:
  release:
    types: [published]

jobs:
  release:
    runs-on: "ubuntu-latest"
    env:
        TWINE_USERNAME: "__token__"
        TWINE_PASSWORD: ${{ secrets.PYPI_TOKEN }}
    steps:
      - uses: "actions/checkout@v2"
      - run: |
          python -m pip install build twine invoke
          python -m invoke publish
