---
name: Release

on:
  release:
    types: [published]

jobs:
  release:
    runs-on: "ubuntu-latest"
    steps:
      - uses: "actions/checkout@v2"
      - run: |
          python -m pipx install build
          python -m pipx install twine
          python -m pipx install invoke
          python -m invoke publish
