---
name: Release

on:
  release:
    types: [published]
permissions:
  contents: write

jobs:
  release:
    runs-on: "ubuntu-latest"
    env:
        TWINE_USERNAME: "__token__"
        TWINE_PASSWORD: ${{ secrets.PYPI_TOKEN }}
    steps:
      - uses: "actions/checkout@v3"
        name: "Build and Publish"
      - run: |
          python -m pip install -r requirements/dev_requirements.txt
          python -m pip install .
          python -m invoke publish
