---
name: CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
  workflow_dispatch:

jobs:
  tests:
    runs-on: "ubuntu-latest"
    steps:
      - uses: "actions/checkout@v2"
      - uses: wntrblm/nox@2023.04.22
      - run: |
          python -m pip install -r requirements/dev_requirements.txt
          python -m invoke test
